LASTFM_USERNAME = 'YOUR_LASTFM_USERNAME'
LASTFM_PASS = 'YOUR_HASHED_LASTFM_PASS'
SPOTIFY_USERNAME = 'YOUR_SPOTIFY_USERNAME'

LASTFM_API_KEY = 'YOUR_LASTFM_API_KEY'
LASTFM_API_SECRET = 'YOUR_LASTFM_API_SECRET'
SPOTIFY_CLIENT_ID = 'YOUR_SPOTIFY_CLIENT_ID'
SPOTIFY_CLIENT_SECRET = 'YOUR_SPOTIFY_CLIENT_SECRET'
